AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for lambda-model

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 45
    MemorySize: 256 
    Environment:
      Variables:
        APCA_API_KEY_ID: !Ref AlpacaApiKeyId
        APCA_API_SECRET_KEY: !Ref AlpacaApiSecretKey
        APCA_API_BASE_URL: !Ref  AlpacaBaseUrl

Parameters:
  AlpacaApiKeyId:
    Type: String
    NoEcho: true
    Default: 'PKURSNA8VBJCVS1D3VQC'
  AlpacaApiSecretKey:
    Type: String
    NoEcho: true
    Default: 'OloIpUnz4pWBeimvX1ueEyYZmni99WQAHzzeWq5m'
  AlpacaBaseUrl:
    Type: String
    Default: 'https://paper-api.alpaca.markets'

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{ticker}/{date}
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/inferenceFunction
      DockerTag: python3.8-v1